# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a025ee5bf04c9a8c7de64d69a502b549497adcf0b45fe5704e9119f8e237b85f8c9faf804b1ea3269208a38be2537688a0e6a3822c283b0f8b3e472d36170895

test:
  secret_key_base: 66dff9eeb7719102b0e12bd28159be0b82917fc3dfe7b6fec7af40b6c297b0884d93b86bb28c3d518e2c462ce0149e1df158cecda43c65400482473659c82a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
